version: "3"

services:
  react:
    build: frontend
    ports:
      - 4050:4050
    depends_on:
      - express
    volumes:
      - ./frontend/:/app
      - frontendnodemodules:/app/node_modules
    container_name: soundwave-frontend-container

  express:
    build:
      context: backend
    ports:
      - 4040:4040
    volumes:
      - ./backend/:/app
      - backendnodemodules:/app/node_modules
    container_name: soundwave-backend-container

volumes:
  backendnodemodules: {}
  frontendnodemodules: {}
