version: "3.8"

services:
  react:
    build: frontend
    ports:
      - 3000:3000
    depends_on:
      - express
    volumes:
      - ./frontend/:/app
      - frontendnodemodules:/app/node_modules
    container_name: frontend-container

  express:
    build:
      context: backend
    ports:
      - 4040:4040
    volumes:
      - ./backend/:/app
      - backendnodemodules:/app/node_modules
    container_name: backend-container

volumes:
  backendnodemodules: {}
  frontendnodemodules: {}
