version: '3.8'

services:
  react:
    build:
      context: frontend
      target: ui-dev
    ports:
      - 4050:4050
    networks:
      - public
    depends_on:
      - express
    volumes:
      - ./frontend/:/app
      - ./frontend/node_modules:/app/node_modules
    container_name: soundchat-frontend

  express:
    build:
      context: backend
      target: server-dev
    ports:
      - 4040:4040
    networks:
      - public
    volumes:
      - ./backend/:/app
      - ./backend/node_modules:/app/node_modules
    container_name: soundchat-backend

networks:
  public:
    driver: bridge
