#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

cd backend
npm run lint
npm run format
echo "backend done and done!"
# cd ../frontend
# npm run lint
# npm run format
# echo "frontend done and done!"
# cd ../
echo "root 😎"