#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

cd backend
npm run lint
npm run format
echo "✅  Backend done and done!"
# cd ../frontend
# npm run lint
# npm run format
# echo "✅  Frontend done and done!"
cd ../
echo "Root 😎"