#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

cd backend
npm run lint
echo "✅  Backend done and done!"
cd ../frontend
npm run lint
echo "✅  Frontend done and done!"
cd ../
npm run format
printf "\n⭐  root 😎\n"